import { PrismaClient } from '../../src/generated/prisma/client.js';

// leisureItemName : nom exact de l'établissement dans leisureSeeder.ts
// undefined = pas de lien établissement
const dealsData: Array<{
  countryCode: string;
  title: string;
  description: string;
  category: string;
  originalPrice: number;
  discountedPrice: number;
  discount: number;
  validUntil: string;
  location: string;
  image: string;
  isPopular: boolean;
  merchantName: string;
  tags: string;
  availableQuantity: number;
  maxQuantity: number;
  rating: number;
  reviewCount: number;
  status: string;
  leisureItemName?: string;
}> = [

  // ═══════════════════════════════════════════════════════════════
  //  🇨🇬  CONGO (CG)
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: 'CG',
    title: 'Dîner Gastronomique au Restaurant Le Jardin',
    description: 'Menu 3 services avec vue sur le fleuve Congo. Découvrez une cuisine raffinée dans un cadre exceptionnel avec des produits locaux de première qualité.',
    category: 'restaurants',
    originalPrice: 45000,
    discountedPrice: 31500,
    discount: 30,
    validUntil: '2026-08-15',
    location: 'Brazzaville Centre',
    image: 'https://images.unsplash.com/photo-1559964114-f8b3d8c8b41c?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Restaurant Le Jardin',
    tags: JSON.stringify(['Restaurant', 'Gastronomie', 'Vue fleuve']),
    availableQuantity: 45,
    maxQuantity: 100,
    rating: 4.8,
    reviewCount: 127,
    status: 'published',
    leisureItemName: 'Restaurant Le Jardin',
  },
  {
    countryCode: 'CG',
    title: 'Séance de SPA Détente Complète',
    description: 'Massage relaxant de 60 minutes + accès au sauna et hammam. Évadez-vous du stress quotidien dans notre espace zen.',
    category: 'activities',
    originalPrice: 25000,
    discountedPrice: 15000,
    discount: 40,
    validUntil: '2026-09-01',
    location: 'Pointe-Noire',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1080&q=80&fit=crop',
    isPopular: false,
    merchantName: 'Zen Wellness Center',
    tags: JSON.stringify(['Spa', 'Relaxation', 'Bien-être']),
    availableQuantity: 12,
    maxQuantity: 50,
    rating: 4.6,
    reviewCount: 89,
    status: 'published',
    leisureItemName: 'Zen Wellness Center',
  },
  {
    countryCode: 'CG',
    title: 'Week-end Découverte à Loango',
    description: 'Excursion 2 jours/1 nuit au Parc National de Loango avec guide. Observation des éléphants de mer et tortues marines.',
    category: 'feeti-na-feeti',
    originalPrice: 120000,
    discountedPrice: 84000,
    discount: 30,
    validUntil: '2026-10-30',
    location: 'Parc National Loango',
    image: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Congo Safari Tours',
    tags: JSON.stringify(['Nature', 'Safari', 'Aventure']),
    availableQuantity: 8,
    maxQuantity: 20,
    rating: 4.9,
    reviewCount: 234,
    status: 'published',
    leisureItemName: 'Congo Safari Tours',
  },
  {
    countryCode: 'CG',
    title: 'Cours de Cuisine Locale avec Chef',
    description: 'Apprenez à préparer les plats traditionnels congolais avec un chef renommé. Ingrédients et recettes inclus.',
    category: 'weekly',
    originalPrice: 18000,
    discountedPrice: 11700,
    discount: 35,
    validUntil: '2026-07-31',
    location: 'Brazzaville',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Chef Mbemba Academy',
    tags: JSON.stringify(['Cuisine', 'Culture', 'Apprentissage']),
    availableQuantity: 6,
    maxQuantity: 15,
    rating: 4.7,
    reviewCount: 56,
    status: 'published',
  },
  {
    countryCode: 'CG',
    title: 'Concert Privé Feeti Sessions',
    description: 'Soirée musicale exclusive avec des artistes locaux émergents. Ambiance intimiste et authentique dans un lieu secret.',
    category: 'feeti-na-feeti',
    originalPrice: 8000,
    discountedPrice: 4800,
    discount: 40,
    validUntil: '2026-08-20',
    location: 'Brazzaville - Poto-Poto',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1080&q=80&fit=crop',
    isPopular: false,
    merchantName: 'Rooftop Sky Lounge',
    tags: JSON.stringify(['Musique', 'Local', 'Exclusif']),
    availableQuantity: 25,
    maxQuantity: 50,
    rating: 4.5,
    reviewCount: 42,
    status: 'published',
    leisureItemName: 'Rooftop Sky Lounge',
  },
  {
    countryCode: 'CG',
    title: "Nuit d'Hôtel de Luxe + Petit Déjeuner",
    description: "Séjour d'une nuit dans notre suite Premium avec vue panoramique sur le fleuve et petit déjeuner continental.",
    category: 'hotels',
    originalPrice: 75000,
    discountedPrice: 52500,
    discount: 30,
    validUntil: '2026-09-30',
    location: 'Brazzaville - Bord de Fleuve',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Hôtel Maya Maya',
    tags: JSON.stringify(['Luxe', 'Vue fleuve', 'Romance']),
    availableQuantity: 5,
    maxQuantity: 10,
    rating: 4.8,
    reviewCount: 198,
    status: 'published',
    leisureItemName: 'Hôtel Maya Maya',
  },
  {
    countryCode: 'CG',
    title: 'Shopping Spree Centre Commercial',
    description: "Bon d'achat de 50 000 FCFA valable dans tous les magasins du centre commercial + parking gratuit.",
    category: 'shopping',
    originalPrice: 50000,
    discountedPrice: 40000,
    discount: 20,
    validUntil: '2026-12-31',
    location: 'Brazzaville Centre',
    image: 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=1080&q=80&fit=crop',
    isPopular: false,
    merchantName: 'Centre Commercial Mbochi',
    tags: JSON.stringify(['Shopping', 'Mode', 'Lifestyle']),
    availableQuantity: 100,
    maxQuantity: 200,
    rating: 4.2,
    reviewCount: 76,
    status: 'published',
  },

  // ═══════════════════════════════════════════════════════════════
  //  🇨🇩  RDC (CD)
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: 'CD',
    title: 'Buffet Kinois All-Inclusive',
    description: 'Buffet à volonté avec les spécialités culinaires de Kinshasa : poulet moambé, fumbwa, pondu et bien plus.',
    category: 'restaurants',
    originalPrice: 30000,
    discountedPrice: 18000,
    discount: 40,
    validUntil: '2026-08-31',
    location: 'Kinshasa - Gombe',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Restaurant Chez Mama Jeanne',
    tags: JSON.stringify(['Buffet', 'Cuisine locale', 'Famille']),
    availableQuantity: 30,
    maxQuantity: 80,
    rating: 4.7,
    reviewCount: 165,
    status: 'published',
    leisureItemName: 'Restaurant Chez Mama Jeanne',
  },
  {
    countryCode: 'CD',
    title: 'Excursion au Fleuve Congo en Pirogue',
    description: 'Balade de 3h sur le fleuve Congo avec guide local. Visite des îles et rencontre avec les pêcheurs. Déjeuner inclus.',
    category: 'feeti-na-feeti',
    originalPrice: 40000,
    discountedPrice: 26000,
    discount: 35,
    validUntil: '2026-10-15',
    location: 'Kinshasa - Fleuve Congo',
    image: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Congo River Tours',
    tags: JSON.stringify(['Nature', 'Fleuve', 'Culture']),
    availableQuantity: 15,
    maxQuantity: 30,
    rating: 4.9,
    reviewCount: 88,
    status: 'published',
  },
  {
    countryCode: 'CD',
    title: 'Séjour Hôtel 4 Étoiles Kinshasa',
    description: "2 nuits en chambre double avec petit déjeuner dans l'un des meilleurs hôtels de Kinshasa. Piscine et spa inclus.",
    category: 'hotels',
    originalPrice: 150000,
    discountedPrice: 97500,
    discount: 35,
    validUntil: '2026-09-30',
    location: 'Kinshasa - Gombe',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Hôtel Fleuve Congo',
    tags: JSON.stringify(['Luxe', 'Piscine', 'Business']),
    availableQuantity: 10,
    maxQuantity: 25,
    rating: 4.6,
    reviewCount: 312,
    status: 'published',
    leisureItemName: 'Hôtel Fleuve Congo',
  },
  {
    countryCode: 'CD',
    title: 'Session Gaming VR & Tournoi',
    description: "Passez 2h au Gaming Lounge avec accès réalité virtuelle et participation au tournoi hebdomadaire. Boissons offertes.",
    category: 'activities',
    originalPrice: 12000,
    discountedPrice: 7800,
    discount: 35,
    validUntil: '2026-08-31',
    location: 'Kinshasa - Ngaliema',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Gaming Lounge Kinshasa',
    tags: JSON.stringify(['Gaming', 'VR', 'Jeunes', 'Tournoi']),
    availableQuantity: 20,
    maxQuantity: 50,
    rating: 4.4,
    reviewCount: 78,
    status: 'published',
    leisureItemName: 'Gaming Lounge Kinshasa',
  },

  // ═══════════════════════════════════════════════════════════════
  //  🇬🇦  GABON (GA)
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: 'GA',
    title: 'Plongée Sous-Marine à Cap Lopez',
    description: 'Session de plongée découverte avec moniteur certifié PADI. Exploration des récifs coralliens et de la vie marine gabonaise.',
    category: 'activities',
    originalPrice: 60000,
    discountedPrice: 39000,
    discount: 35,
    validUntil: '2026-09-30',
    location: 'Port-Gentil - Cap Lopez',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Gabon Dive Center',
    tags: JSON.stringify(['Plongée', 'Océan', 'Aventure']),
    availableQuantity: 8,
    maxQuantity: 20,
    rating: 4.9,
    reviewCount: 67,
    status: 'published',
    leisureItemName: 'Gabon Dive Center',
  },
  {
    countryCode: 'GA',
    title: 'Dîner Vue sur Estuaire + Cocktail',
    description: "Soirée gastronomique avec vue panoramique sur l'estuaire du Gabon. Menu 4 services + cocktail de bienvenue.",
    category: 'restaurants',
    originalPrice: 55000,
    discountedPrice: 38500,
    discount: 30,
    validUntil: '2026-08-31',
    location: 'Libreville - Bord de Mer',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1080&q=80&fit=crop',
    isPopular: false,
    merchantName: 'Radisson Blu Libreville',
    tags: JSON.stringify(['Gastronomie', 'Vue mer', 'Romantic']),
    availableQuantity: 20,
    maxQuantity: 40,
    rating: 4.5,
    reviewCount: 93,
    status: 'published',
    leisureItemName: 'Radisson Blu Libreville',
  },
  {
    countryCode: 'GA',
    title: 'Safari Parc National de la Lopé',
    description: "3 jours/2 nuits de safari dans le Parc National de la Lopé. Observation des gorilles, éléphants et mandrill.",
    category: 'feeti-na-feeti',
    originalPrice: 250000,
    discountedPrice: 175000,
    discount: 30,
    validUntil: '2026-11-30',
    location: 'Parc National de la Lopé',
    image: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Lopé Eco-Tourism',
    tags: JSON.stringify(['Safari', 'Gorilles', 'Écotourisme']),
    availableQuantity: 6,
    maxQuantity: 12,
    rating: 5.0,
    reviewCount: 45,
    status: 'published',
  },
  {
    countryCode: 'GA',
    title: 'Soirée Bowling & Bar Galaxie',
    description: "Partie de bowling illimitée (2h) + 1 cocktail offert au bar. Parfait pour une sortie entre amis ou en famille.",
    category: 'activities',
    originalPrice: 18000,
    discountedPrice: 11700,
    discount: 35,
    validUntil: '2026-09-30',
    location: 'Libreville',
    image: 'https://images.unsplash.com/photo-1529494792912-8ae2f7e8e1e5?w=1080&q=80&fit=crop',
    isPopular: false,
    merchantName: 'Bowling Galaxie',
    tags: JSON.stringify(['Bowling', 'Famille', 'Gabon', 'Sortie']),
    availableQuantity: 30,
    maxQuantity: 60,
    rating: 4.3,
    reviewCount: 112,
    status: 'published',
    leisureItemName: 'Bowling Galaxie',
  },

  // ═══════════════════════════════════════════════════════════════
  //  🇨🇮  CÔTE D'IVOIRE (CI)
  // ═══════════════════════════════════════════════════════════════
  {
    countryCode: 'CI',
    title: 'Atelier Batik & Wax Ivoirien',
    description: "Apprenez l'art du tissu wax et du batik avec des artisans ivoiriens. Repartez avec votre création personnalisée.",
    category: 'activities',
    originalPrice: 20000,
    discountedPrice: 13000,
    discount: 35,
    validUntil: '2026-09-30',
    location: 'Abidjan - Cocody',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1080&q=80&fit=crop',
    isPopular: false,
    merchantName: 'Atelier Couleurs Ivoire',
    tags: JSON.stringify(['Artisanat', 'Wax', 'Créativité']),
    availableQuantity: 10,
    maxQuantity: 20,
    rating: 4.7,
    reviewCount: 34,
    status: 'published',
  },
  {
    countryCode: 'CI',
    title: 'Brunch Ivoirien Premium le Weekend',
    description: "Brunch dominical avec les spécialités ivoiriennes : alloco, kedjenou, attiéké et jus de gingembre frais.",
    category: 'restaurants',
    originalPrice: 22000,
    discountedPrice: 13200,
    discount: 40,
    validUntil: '2026-08-31',
    location: 'Abidjan - Plateau',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Le Maquis du Plateau',
    tags: JSON.stringify(['Brunch', 'Weekend', 'Local']),
    availableQuantity: 40,
    maxQuantity: 80,
    rating: 4.8,
    reviewCount: 221,
    status: 'published',
    leisureItemName: 'Le Maquis du Plateau',
  },
  {
    countryCode: 'CI',
    title: 'Journée Découverte Grand-Bassam',
    description: "Excursion à Grand-Bassam, ancienne capitale et site UNESCO. Visite guidée, déjeuner fruits de mer et bain de mer.",
    category: 'general',
    originalPrice: 35000,
    discountedPrice: 22750,
    discount: 35,
    validUntil: '2026-10-31',
    location: 'Grand-Bassam',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'CI Discover Tours',
    tags: JSON.stringify(['UNESCO', 'Histoire', 'Plage']),
    availableQuantity: 20,
    maxQuantity: 40,
    rating: 4.6,
    reviewCount: 158,
    status: 'published',
  },
  {
    countryCode: 'CI',
    title: 'Soirée Afrobeats VIP + Table',
    description: "Entrée VIP + table réservée pour 4 personnes au Club Afrobeats Abidjan. Service bouteille inclus. Dress code obligatoire.",
    category: 'general',
    originalPrice: 80000,
    discountedPrice: 56000,
    discount: 30,
    validUntil: '2026-08-31',
    location: 'Abidjan - Marcory',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1080&q=80&fit=crop',
    isPopular: true,
    merchantName: 'Club Afrobeats Abidjan',
    tags: JSON.stringify(['Nuit', 'VIP', 'Afrobeats', 'Club']),
    availableQuantity: 8,
    maxQuantity: 20,
    rating: 4.6,
    reviewCount: 445,
    status: 'published',
    leisureItemName: 'Club Afrobeats Abidjan',
  },
  {
    countryCode: 'CI',
    title: 'Abonnement Fitness 1 Mois',
    description: "1 mois d'accès illimité au FitLife Club : salle de cardio, musculation, cours collectifs yoga et zumba. Bilan fitness offert.",
    category: 'activities',
    originalPrice: 30000,
    discountedPrice: 19500,
    discount: 35,
    validUntil: '2026-09-30',
    location: 'Abidjan - Cocody',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1080&q=80&fit=crop',
    isPopular: false,
    merchantName: 'FitLife Club',
    tags: JSON.stringify(['Fitness', 'Sport', 'Santé', 'Coaching']),
    availableQuantity: 25,
    maxQuantity: 50,
    rating: 4.5,
    reviewCount: 134,
    status: 'published',
    leisureItemName: 'FitLife Club',
  },
];

export async function seedDeals(prisma: PrismaClient, adminId: string) {
  await prisma.deal.deleteMany({ where: { createdById: adminId } });

  // Charger tous les loisirs pour faire les liens
  const allLeisure = await prisma.leisureItem.findMany({ select: { id: true, name: true, location: true, image: true } });
  const leisureByName = new Map(allLeisure.map(li => [li.name, li]));

  let count = 0;
  let linked = 0;

  for (const { leisureItemName, ...dealFields } of dealsData) {
    const leisure = leisureItemName ? leisureByName.get(leisureItemName) : undefined;

    await prisma.deal.create({
      data: {
        ...dealFields,
        createdById: adminId,
        ...(leisure ? {
          leisureItemId: leisure.id,
          // Auto-aligner location et image sur l'établissement lié
          location: leisure.location,
          image: dealFields.image ?? leisure.image ?? undefined,
        } : {}),
      },
    });

    count++;
    if (leisure) linked++;
  }

  const byCountry: Record<string, number> = {};
  dealsData.forEach(d => { byCountry[d.countryCode] = (byCountry[d.countryCode] ?? 0) + 1; });

  console.log(`✅ ${count} bons plans créés (${linked} liés à un établissement) :`);
  for (const [code, n] of Object.entries(byCountry)) {
    console.log(`   • ${code} — ${n} bons plans`);
  }
}
